require('plugins')
require('nv-globals')
require('nv-utils')
vim.cmd('luafile ~/.config/nvim/nv-settings.lua')
require('nv-autocommands')
require('settings')
require('keymappings')
require('colorscheme')
require('nv-galaxyline')
require('nv-comment')
require('nv-colorizer')
-- require('nv-compe')
require('nv-barbar')
require('nv-telescope')
require('nv-treesitter')
require('nv-autopairs')
require('nv-which-key')
require('nv-dial')
require('nv-rooter')
require('nv-neogit')
require('nv-gitsigns')

vim.cmd('source ~/.config/nvim/vimscript/functions.vim')
require('nv-lspinstall')

-- LSP
require('lsp')
require('lsp.lua-ls')
require('lsp.json-ls')
require('lsp.bash-ls')
require('lsp.clangd')
require('lsp.css-ls')
require('lsp.python-ls')
require('lsp.docker-ls')
require('lsp.js-ts-ls')
require('lsp.vim-ls')
require('lsp.vue-ls')
require('lsp.yaml-ls')
