
-- NOTE: Needs to be fixed for new lsp.config method if normal doesnt work
-- vim.lsp.config("volar", {
--   local get_typescript_server_path = function (root_dir)
--     -- local global_ts = "$PNPM_HOME/global/5"
--     local global_ts =
--       vim.fn.expand("$HOME/.local/share/pnpm/global/5/node_modules/typescript/lib")
--     -- local global_ts = "/usr/local/lib"
--     local found_ts = ""
--     local function check_dir(path)
--       found_ts = util.path.join(path, "node_modules", "typescript", "lib")
--       if util.path.exists(found_ts) then
--         return path
--       end
--     end
--
--     if util.search_ancestors(root_dir, check_dir) then
--       return found_ts
--     else
--       util.path.exists(global_ts)
--       -- vim.notify("Using global typescript")
--       return global_ts
--     end
--   end
--   lspconfig.volar.setup({
--     capabilities = lsp_defaults.capabilities,
--     init_options = {
--       typescript = {
--         tsdk = get_typescript_server_path(vim.fn.getcwd()),
--       },
--       vue = {
--         hybridMode = true,
--       },
--     },
--     on_new_config = function (new_config, new_root_dir)
--       new_config.init_options.typescript.tsdk = get_typescript_server_path(new_root_dir)
--     end,
--   })
